global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# In order to scrape the luigi server, this should scrape the luigimetrics server instead.
scrape_configs:
  - job_name: 'luigi'

    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:5000']

